Added controller unit tests

diff --git a/unittest.in b/unittest.in
--- a/unittest.in
+++ b/unittest.in
@@ -42,6 +42,12 @@ function testGraph()
     testGraphResult=$?
 }
 
+function testController()
+{
+    @EXECUTABLE_OUTPUT_PATH@/Rcs -m 6 -valgrind -nTests 2 -dl -1 > /dev/null
+    testControllerResult=$?
+}
+
 echo -n "Testing mathematics functions ... "
 testMath
 
@@ -55,6 +61,8 @@ else
   echo "failed with $testMathResult errors" 
 fi
 
+
+
 echo -n "Testing graph functions       ... "
 testGraph
 
@@ -66,5 +74,20 @@ then
   echo "failed with more than 255 errors"
 else
   echo "failed with $testGraphResult errors" 
+fi
+
+
+
+echo -n "Testing controller functions  ... "
+testController
+
+if [ $testControllerResult -eq 0 ]
+then
+  echo "succeeded"
+elif [ $testControllerResult -eq 255 ]
+then
+  echo "failed with more than 255 errors"
+else
+  echo "failed with $testControllerResult errors" 
 fi
 
